version: "3"
services:
  database:
    image: postgres:10.17
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=1234teste"
      - "POSTGRES_DB=dbServer"
    ports:
      - 5441:5432
  springboot-app:
    depends_on:
      - database
    image: springbooot-app
    restart: always
    build: .
    ports:
      - 18090:8090
