spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    url: jdbc:postgresql://database:5432/dbServer
    username: postgres
    password: 1234teste
    driverClassName: org.postgresql.Driver
server:
  port: 8090
  servlet:
    context-path: /votingService/v1